name: Reorganize README

on:
  push:
    branches: [master]

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate table with `lpm`
        run: |
          wget https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/v0.95/lpm.x86_64-linux -O lpm
          chmod +x lpm
          ./lpm table manifest.json README.md
      - name: Set environment variables
        run: |
          set +e # need to disable this
          git diff --exit-code -s README.md
          echo "has_diff=$?" >> $GITHUB_ENV
      - name: create PR
        if: env.has_diff == 1
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Reorganize README.md
          branch: reorganize-ci
          add-paths: README.md
          delete-branch: false
          title: '[CI] Reorganize README.md'
          body: |
            This is a CI that makes sure entries match the specified manifest.
            Please check the [CI run][1] for logs.

            [1]: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
